[['sein', 'sein', 'ist', 'war', 'gewesen', 'be'],
['haben', 'haben', 'hat', 'hatte', 'gehabt', 'have'],
['werden', 'sein', 'wird', 'wurde', {'geworden', 'worden'}, 'become'],
['können', 'haben', 'kann', 'konnte', 'gekonnt', 'can, be able to'],
['müssen', 'haben', {'muß', 'muss'}, 'musste', 'gemusst', 'must, have to'],
['sagen', 'haben', 'sagt', 'sagte', 'gesagt', 'say'],
['machen', 'haben', 'macht', 'machte', 'gemacht', 'do, make'],
['geben', 'haben', 'gibt', 'gab', 'gegeben', 'give'],
['kommen', 'sein', 'kommt', 'kam', 'gekommen', 'come'],
['sollen', 'haben', 'soll', 'sollte', 'gesollt', 'should, ought to'],
['wollen', 'haben', 'will', 'wollte', 'gewollt', 'want'],
['gehen', 'sein', 'geht', 'ging', 'gegangen', 'go'],
['wissen', 'haben', 'weiß', 'wusste', 'gewusst', 'know'],
['sehen', 'haben', 'sieht', 'sah', 'gesehen', 'see'],
['lassen', 'haben', 'lässt', 'ließ', 'gelassen', 'let, allow'],
['stehen', 'haben/sein', 'steht', 'stand', 'gestanden', 'stand'],
['finden', 'haben', 'findet', 'fand', 'gefunden', 'find'],
['bleiben', 'sein', 'bleibt', 'blieb', 'geblieben', 'stay, remain'],
['liegen', 'haben/sein', 'liegt', 'lag', 'gelegen', 'lie, be lying'],
['heißen', 'haben', 'heißt', 'hieß', {'geheißen', 'geheißt'}, 'be called'],
['denken', 'haben', 'denkt', 'dachte', 'gedacht', 'think'],
['nehmen', 'haben', 'nimmt', 'nahm', 'genommen', 'take'],
['tun', 'haben', 'tut', 'tat', 'getan', 'do'],
['dürfen', 'haben', 'darf', 'durfte', 'gedurft', 'may, be allowed'],
['glauben', 'haben', 'glaubt', 'glaubte', 'geglaubt', 'believe'],
['halten', 'haben', 'hält', 'hielt', 'gehalten', 'stop, hold'],
['nennen', 'haben', 'nennt', 'nannte', 'genannt', 'name, call (a name)'],
['mögen', 'haben', 'mag', 'mochte', 'gemocht', 'like'],
['zeigen', 'haben', 'zeigt', 'zeigte', 'gezeigt', 'show'],
['führen', 'haben', 'führt', 'führte', 'geführt', 'lead'],
['sprechen', 'haben', 'spricht', 'sprach', 'gesprochen', 'speak'],
['bringen', 'haben', 'bringt', 'brachte', 'gebracht', 'bring, take'],
['leben', 'haben', 'lebt', 'lebte', 'gelebt', 'live'],
['fahren', 'haben/sein', 'fährt', 'fuhr', 'gefahren', 'drive, ride, go'],
['meinen', 'haben', 'meint', 'meinte', 'gemeint', 'think, have an opinion'],
['fragen', 'haben', 'fragt', 'fragte', 'gefragt', 'ask'],
['kennen', 'haben', 'kennt', 'kannte', 'gekannt', 'know'],
['gelten', 'haben', 'gilt', 'galt', 'gegolten', 'be valid'],
['stellen', 'haben', 'stellt', 'stellte', 'gestellt', 'place, set'],
['spielen', 'haben', 'spielt', 'spielte', 'gespielt', 'play'],
['arbeiten', 'haben', 'arbeitet', 'arbeitete', 'gearbeitet', 'work'],
['brauchen', 'haben', 'braucht', 'brauchte', 'gebraucht', 'need'],
['folgen', 'haben/sein', 'folgt', 'folgte', 'gefolgt', 'follow'],
['lernen', 'haben', 'lernt', 'lernte', 'gelernt', 'learn'],
['bestehen', 'haben', 'besteht', 'bestand', 'bestanden', 'exist, insist, pass (an exam)'],
['verstehen', 'haben', 'versteht', 'verstand', 'verstanden', 'understand'],
['setzen', 'haben/sein', 'setzt', 'setzte', 'gesetzt', 'set, put, place'],
['bekommen', 'haben/sein', 'bekommt', 'bekam', 'bekommen', 'get, receive'],
['beginnen', 'haben', 'beginnt', 'begann', 'begonnen', 'begin'],
['erzählen', 'haben', 'erzählt', 'erzählte', 'erzählt', 'narrate, tell'],
['versuchen', 'haben', 'versucht', 'versuchte', 'versucht', 'try, attempt'],
['schreiben', 'haben', 'schreibt', 'schrieb', 'geschrieben', 'write'],
['laufen', 'haben/sein', 'läuft', 'lief', 'gelaufen', 'run'],
['erklären', 'haben', 'erklärt', 'erklärte', 'erklärt', 'explain'],
['entsprechen', 'haben', 'entspricht', 'entsprach', 'entsprochen', 'correspond'],
['sitzen', 'haben/sein', 'sitzt', 'saß', 'gesessen', 'sit'],
['ziehen', 'haben/sein', 'zieht', 'zog', 'gezogen', 'pull, move'],
['scheinen', 'haben', 'scheint', 'schien', 'geschienen', 'shine, seem, appear'],
['fallen', 'sein', 'fällt', 'fiel', 'gefallen', 'fall'],
['gehören', 'haben', 'gehört', 'gehörte', 'gehört', 'belong'],
['entstehen', 'sein', 'entsteht', 'entstand', 'entstanden', 'originate, develop'],
['erhalten', 'haben', 'erhält', 'erhielt', 'erhalten', 'receive'],
['treffen', 'haben/sein', 'trifft', 'traf', 'getroffen', 'meet'],
['suchen', 'haben', 'sucht', 'suchte', 'gesucht', 'search, look for'],
['legen', 'haben', 'legt', 'legte', 'gelegt', 'lay, put'],
['vor|stellen', 'haben', 'vorstellt', 'vorstellte', 'vorgestellt', 'introduce, imagine'],
['handeln', 'haben', 'handelt', 'handelte', 'gehandelt', 'deal, trade'],
['erreichen', 'haben', 'erreicht', 'erreichte', 'erreicht', 'achieve, reach'],
['tragen', 'haben', 'trägt', 'trug', 'getragen', 'carry, wear'],
['schaffen', 'haben', 'schafft', 'schaffte', 'geschafft', 'manage'],
['schaffen', 'haben', 'schafft', 'schuf', 'geschaffen', 'create'],
['lesen', 'haben', 'liest', 'las', 'gelesen', 'read'],
['verlieren', 'haben', 'verliert', 'verlor', 'verloren', 'lose'],
['dar|stellen', 'haben', 'darstellt', 'darstellte', 'dargestellt', 'depict, portray'],
['erkennen', 'haben', 'erkennt', 'erkannte', 'erkannt', 'recognize, admit'],
['entwickeln', 'haben', 'entwickelt', 'entwickelte', 'entwickelt', 'develop'],
['reden', 'haben', 'redet', 'redete', 'geredet', 'talk'],
['aus|sehen', 'haben', 'aussieht', 'aussah', 'ausgesehen', 'appear, look (a certain way)'],
['erscheinen', 'sein', 'erscheint', 'erschien', 'erschienen', 'appear'],
['bilden', 'haben', 'bildet', 'bildete', 'gebildet', 'form, educate'],
['an|fangen', 'haben', 'anfängt', 'anfing', 'angefangen', 'begin'],
['erwarten', 'haben', 'erwartet', 'erwartete', 'erwartet', 'expect'],
['wohnen', 'haben', 'wohnt', 'wohnte', 'gewohnt', 'live'],
['betreffen', 'haben', 'betrifft', 'betraf', 'betroffen', 'affect, concern'],
['warten', 'haben', 'wartet', 'wartete', 'gewartet', 'wait'],
['vergehen', 'haben/sein', 'vergeht', 'verging', 'vergangen', 'elapse, decay'],
['helfen', 'haben', 'hilft', 'half', 'geholfen', 'help'],
['gewinnen', 'haben', 'gewinnt', 'gewann', 'gewonnen', 'win'],
['schließen', 'haben', 'schließt', {'schloss', 'schloß'}, 'geschlossen', 'close'],
['fühlen', 'haben', 'fühlt', 'fühlte', 'gefühlt', 'feel'],
['bieten', 'haben', 'bietet', 'bot', 'geboten', 'offer'],
['interessieren', 'haben', 'interessiert', 'interessierte', 'interessiert', 'interest'],
['erinnern', 'haben', 'erinnert', 'erinnerte', 'erinnert', 'remember'],
['ergeben', 'haben', 'ergibt', 'ergab', 'ergeben', 'result in'],
['an|bieten', 'haben', 'anbietet', 'anbot', 'angeboten', 'offer'],
['studieren', 'haben', 'studiert', 'studierte', 'studiert', 'study'],
['verbinden', 'haben', 'verbindet', 'verband', 'verbunden', 'connect, link'],
['an|sehen', 'haben', 'ansieht', 'ansah', 'angesehen', 'look at, watch'],
['fehlen', 'haben', 'fehlt', 'fehlte', 'gefehlt', 'lack, be missing, be absent'],
['bedeuten', 'haben', 'bedeutet', 'bedeutete', 'bedeutet', 'mean'],
['vergleichen', 'haben', 'vergleicht', 'verglich', 'verglichen', 'compare'],]